Simulation = "BlsFtCosiProtocol"
Servers = 2
Rounds = 10
CloseWait = 6000
Suite = "bn256.g2"
Tags = "vartime"
LoadBlock = false
BlockSize = 1000000

Depth, Hosts, NSubTrees, FailingSubleaders, FailingLeafs
2, 5, 3, 0, 0
