Simulation = "BlsFtCosiProtocol"
Servers = 10
Rounds = 10
CloseWait = 6000
Suite = "bn256.g2"
Tags = "vartime"
FailingSubleaders = 0
FailingLeafs = 0
Depth = 2
LoadBlock = false
Bandwidth = 35
Delay = 100
BlockSize = 2000000

Hosts, NSubTrees
10, 1
25, 2
50, 5
75, 7
100, 10
150, 15
200, 20
250, 25
300, 30
350, 35
400, 40
450, 45
500, 50